[project]
name = "hexlet-code"
version = "0.1.0"
description = "Third project hexlet school"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flack>=1.3.7",
    "gunicorn>=23.0.0",
]

[dependency-groups]
dev = [
    "ruff>=0.12.2",
]
